language: ruby
rvm:
  - 2.3.0
env:
  global:
    secure: Zr7cGMefUFb6G+fc3x80ZWNS27PFuG5AGUncy1QYy18jg5lRwVRqbPa+iqM8Hbk5mmsM1RXJVkFwVJjGSalLpLpDsJPiduYnOd9O6JtuoU9fPjmQDwgBfMg+P7KyZ0L9Q03wG/1fWjIQVCaWXftKFmpWCofgqyUeXfvoioioDsxPK2lSqTiqgGkBRfsqcSV1vKjrMydI5Bb3FQy/mHpKeIR/2PuW4a5RZ3P+JG45uiKG+gj0N3bxvZHMYm110S2q2aRm1EuhAGjwx4z5NH4Jw1XgfanoAjt8JAaJU8fNjIhy9aLKPTHpNdTQNjHJnhDrU1KkFVVdvAP2fki03lZlajKPo/h9I9HhDgOL9BmAe/xs/SyG5SyrwNPpbHm+tY1JdvI/uzMLQKRgPd3lMA9jbEsfIfSosAt3GwrrjbSdcN7MM0bCC8gLGuUZlo2KOI+RN87UgrnHP0BIZclGSDHLDzuRwqTDjJWINqudwUD6HP/wW8mmgSMyaC/jcVrOY885X4XaeIe6UgKv+4CpdLWe2YvAUUI3s0dEAMw/8jZc+q2YiLzR1/1hNswzwe6Dg6z6p/xrL3P3pg083X8ueSOi04Yp92JdV6ZMiwLiXC3J4Bn5CYcfseK1dD7BrAW6TYL0l4yEk+fLQ2Lm8tw/bpCB2HZs2h9P+iIEkMJEkfNatXo=
